version: "3.8"

services:
  gateway:
    image: semirm/go-rabbitmq-gateway:1
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    container_name: medium_gateway
    command:
      - -rmq_host=rabbitmq
      - -db_path=/db/woohoo_orders.db
    ports:
      - "8000:8000"
    volumes:
      - db:/db
    networks:
      - medium
  order:
    image: semirm/go-rabbitmq-order:1
    build:
      context: .
      dockerfile: cmd/order/Dockerfile
    container_name: medium_order
    command:
      - -rmq_host=rabbitmq
      - -db_path=/db/woohoo_orders.db
    volumes:
      - db:/db
    networks:
      - medium
  shipping:
    image: semirm/go-rabbitmq-shipping:1
    build:
      context: .
      dockerfile: cmd/shipping/Dockerfile
    container_name: medium_shipping
    command:
      - -rmq_host=rabbitmq
    volumes:
      - db:/db
    networks:
      - medium
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - medium
volumes:
  db:
networks:
  medium: