version: "3.8"

services:
  order:
    image: semirm/go-rabbitmq-order:1
    build:
      context: .
      dockerfile: cmd/order/Dockerfile
    container_name: medium_order
    ports:
      - "8001:8001"
    networks:
      - medium
  gateway:
    image: semirm/go-rabbitmq-gateway:1
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    container_name: medium_gateway
    ports:
      - "8000:8000"
    depends_on:
      - order
    networks:
      - medium
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - medium
networks:
  medium: